/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import Service.Controller.ClienteController;
import Service.Controller.OrcamentoController;
import Service.Controller.PedidoController;
import Service.Controller.UsuarioController;
import VOs.ClienteVO;
import VOs.Enuns.EnunTipoPedido;
import VOs.OrcamentoVO;
import VOs.PedidoVO;
import VOs.UsuarioVO;
import gextil.config;
import java.sql.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author felli
 */
public class jdCadastraPedido extends javax.swing.JFrame {

    /**
     * Creates new form jdCadastraPedido
     */
    public jdCadastraPedido(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
        initComponents();
        pedCont = new PedidoController();
        clCont = new ClienteController();
        orcCont = new OrcamentoController();
        usrCont = new UsuarioController();

        init();

        List<ClienteVO> clCombo = clCont.getAll();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbClientes.getModel();
        modelo.removeAllElements();
        for (ClienteVO cl : clCombo) {
            modelo.addElement(cl.getNome());
        }

        List<OrcamentoVO> orcCombo = orcCont.getAll();
        DefaultComboBoxModel modPrd = (DefaultComboBoxModel) cbOrcamento.getModel();
        modPrd.removeAllElements();
        for (OrcamentoVO orc : orcCombo) {
            modPrd.addElement(orc.getId() + " - " + orc.getDataEmissao().toString() + " - " + clCont.getById(orc.getCliente()).getNome());
        }

    }

    PedidoController pedCont;
    UsuarioController usrCont;
    ClienteController clCont;
    OrcamentoController orcCont;
    int mode = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDataEmissao = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDiasEntrega = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPedido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbClientes = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnBuscaPedido = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbOrcamento = new javax.swing.JComboBox<>();
        btnVoltar1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastra pedidos");
        setResizable(false);

        jLabel1.setText("Id");

        txtId.setEnabled(false);

        jLabel2.setText("Tipo");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proprio", "Terceiro" }));
        cbTipo.setEnabled(false);

        jLabel3.setText("Data de emissão");

        txtDataEmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtDataEmissao.setText("dd/MM/yyyy");
        txtDataEmissao.setEnabled(false);

        jLabel4.setText("Entrega em");

        txtDiasEntrega.setEnabled(false);

        jLabel5.setText("Nº do pedido");

        txtPedido.setEnabled(false);

        jLabel6.setText("Cliente");

        cbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbClientes.setEnabled(false);

        jLabel7.setText("Usuario");

        txtUsuario.setEnabled(false);

        btnBuscaPedido.setText("Busca de pedidos");
        btnBuscaPedido.setEnabled(false);
        btnBuscaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaPedidoActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Fechar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("Orçamento");

        cbOrcamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbOrcamento.setEnabled(false);

        btnVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/undo.png"))); // NOI18N
        btnVoltar1.setText("Voltar");
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });

        jLabel9.setText("dias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPedido)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbOrcamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbClientes, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDataEmissao, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDiasEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVoltar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiasEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnConfirmar)
                    .addComponent(btnAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnVoltar1)
                    .addComponent(btnExcluir)
                    .addComponent(btnBuscaPedido))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed

        ClienteVO cl = clCont.getByName(cbClientes.getSelectedItem().toString());
        UsuarioVO usr = usrCont.getByName(txtUsuario.getText());
        String selected = (String) cbOrcamento.getSelectedItem();
        int id_orc = Integer.parseInt(selected.split(" - ")[0]);

        long now = System.currentTimeMillis();

        PedidoVO ped = new PedidoVO(EnunTipoPedido.valueOf(cbTipo.getSelectedItem().toString()),
                new Date(now),
                new Date(now + 1000 * 60 * 60 * 24 * Integer.parseInt(txtDiasEntrega.getText())),
                Integer.parseInt(txtPedido.getText()),
                cl.getId(),
                usr.getId(),
                id_orc,
                Integer.parseInt(txtId.getText()));

        switch (mode) {
            case 0: // Insere
                if (verificaObjeto(ped)) {
                    pedCont.insere(ped);
                }
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso.");
                btnVoltar1ActionPerformed(evt);
                break;
            case 1: // Exclui
                pedCont.deletaPorId(Integer.parseInt(txtId.getText()));
                JOptionPane.showMessageDialog(null, "Deletado com sucesso.");
                btnVoltar1ActionPerformed(evt);

                break;
            case 2: // Altera
                pedCont.update(ped);
                JOptionPane.showMessageDialog(null, "Atualizado com sucesso.");
                btnVoltar1ActionPerformed(evt);

                break;
            default:
                break;
        }

    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnBuscaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaPedidoActionPerformed
        PedidoVO ped = new PedidoVO();
        jdConsultaPedido frConsulta = new jdConsultaPedido(this, rootPaneCheckingEnabled, ped);
        frConsulta.setModal(true);
        frConsulta.setLocationRelativeTo(this);
        frConsulta.setVisible(true);

        if (ped.getId() != 0) {

            txtId.setText(String.valueOf(ped.getId()));
            switch (ped.getTipo()) {
                case Proprio:
                    cbTipo.setSelectedIndex(0);
                    break;
                case Terceiro:
                    cbTipo.setSelectedIndex(1);
                    break;
                default:  
                    cbTipo.setSelectedIndex(0);
                    break;
            }
            long dias = (ped.getDataEntrega().getTime() - ped.getDataEmissao().getTime())/(1000*60*60*24);
            
            txtPedido.setText(String.valueOf(ped.getNumPedido()));
            txtUsuario.setText(usrCont.getById(ped.getUsuario()).getUsername());
            txtDataEmissao.setText(ped.getDataEmissao().toString());
            txtDiasEntrega.setText(String.valueOf(dias));
            cbClientes.setSelectedItem(clCont.getById(ped.getCliente()).getNome());
            
            OrcamentoVO orcamento = orcCont.getById(ped.getOrcamento());
            
            String orc = String.valueOf(ped.getOrcamento()) + " - " + 
                    orcamento.getDataEmissao().toString() + " - " +
                    clCont.getById(ped.getCliente()).getNome();
            cbOrcamento.setSelectedItem(orc);           
        }

    }//GEN-LAST:event_btnBuscaPedidoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        mode = 0;
        enableInputs(false, false, true, false, false);
        enableCbs(true, true, true);
        enableBtn(false, true, false);

        btnBuscaPedido.setEnabled(false);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        mode = 1;
        enableInputs(false, false, false, false, false);
        enableCbs(false, false, false);
        enableBtn(false, false, true);

        btnBuscaPedido.setEnabled(true);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        mode = 2;
        enableInputs(false, false, true, false, false);
        enableCbs(false, false, false);
        enableBtn(true, false, false);

        btnBuscaPedido.setEnabled(true);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        enableBtn(true, true, true);
        cleanInputs();
        enableCbs(false, false, false);
        enableInputs(false, false, false, false, false);
        btnBuscaPedido.setEnabled(false);

        init();
    }//GEN-LAST:event_btnVoltar1ActionPerformed

    private void init() {
        txtId.setText(String.valueOf(pedCont.getNextId()));
        txtPedido.setText(String.valueOf(pedCont.getNextNumId()));
        txtUsuario.setText(config.currentUser.getUsername());
        txtDataEmissao.setText(new Date(System.currentTimeMillis()).toString());
    }

    private void cleanInputs() {
        txtId.setText("");
        txtDataEmissao.setText("");
        cbTipo.setSelectedIndex(0);
        txtDiasEntrega.setText("");
        txtPedido.setText("");
        cbClientes.setSelectedIndex(0);
        txtUsuario.setText("");
        cbOrcamento.setSelectedIndex(0);
    }

    private void enableCbs(boolean cbTipo, boolean cbClientes, boolean cbOrcamento) {
        this.cbTipo.setEnabled(cbTipo);
        this.cbClientes.setEnabled(cbClientes);
        this.cbOrcamento.setEnabled(cbOrcamento);
    }

    private void enableInputs(boolean txtId,
            boolean txtDataEmi,
            boolean txtDataEnt,
            boolean txtPedido,
            boolean txtUsername) {
        this.txtId.setEnabled(txtId);
        this.txtDataEmissao.setEnabled(txtDataEmi);
        this.txtDiasEntrega.setEnabled(txtDataEnt);
        this.txtPedido.setEnabled(txtPedido);
        this.txtUsuario.setEnabled(txtUsername);

    }

    private void enableBtn(boolean btnAlterar, boolean btnCadastrar, boolean btnExcluir) {
        this.btnAlterar.setEnabled(btnAlterar);
        this.btnCadastrar.setEnabled(btnCadastrar);
        this.btnExcluir.setEnabled(btnExcluir);
    }

    private boolean verificaObjeto(PedidoVO ped) {
        if (ped.getTipo() == null) {
            return false;
        } else if (ped.getDataEmissao() == null || ped.getDataEmissao().toString().isEmpty()) {
            return false;
        } else if (ped.getDataEntrega() == null || ped.getDataEntrega().toString().isEmpty()) {
            return false;
        } else if (ped.getNumPedido() <= 0) {
            return false;
        } else if (ped.getCliente() <= 0) {
            return false;
        } else if (ped.getUsuario() <= 0) {
            return false;
        } else if (ped.getOrcamento() <= 0) {
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdCadastraPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdCadastraPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdCadastraPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdCadastraPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdCadastraPedido dialog = new jdCadastraPedido(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscaPedido;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar1;
    private javax.swing.JComboBox<String> cbClientes;
    private javax.swing.JComboBox<String> cbOrcamento;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField txtDataEmissao;
    private javax.swing.JFormattedTextField txtDiasEntrega;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPedido;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
